version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cineplusdb
      MYSQL_USER: cineplus
      MYSQL_PASSWORD: cineplus
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
volumes:
  dbdata:
